# Generated by Django 4.2.3 on 2023-07-30 07:42

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('ingredients', models.CharField(max_length=255)),
                ('images', models.ImageField(blank=True, null=True, upload_to=recipe.models.userpath)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
